### ISSUE TITLE
Leaves a tmp* directory in application root

### ISSUE THREAD

**Issue by RobLoach** [drupal-composer/drupal-scaffold#33]
After running `composer run-script drupal-scaffold`, a `tmp17445153111460235384` directory is left in the application root. Is the directory not cleaned up?
```
 [FileSystem\DeleteDir] Deleted /tmp//drupal-scaffold-1460235378...
 [FileSystem\FilesystemStack] _chmod ["\/home\/rob\/Documents\/playbox\/web\/sites\/default",493]
```

**Comment by webflo** [comment]
I tried to reproduce the bug report, but failed. Could you give me more information about your setup/os?

**Comment by RobLoach** [comment]
[Source](https://github.com/kalamuna/playbox/tree/8), [Log](https://gist.github.com/RobLoach/9abf309ecad12abbc113e32a8483bdd3)
Linux Jarvis 4.2.0-35-generic #40-Ubuntu SMP Tue Mar 15 22:15:45 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

![scaffold](https://cloud.githubusercontent.com/assets/25086/14407816/41ac03de-fea4-11e5-8fd9-8378a2ac6647.png)

I'm likely using the [Composer scripts](https://getcomposer.org/doc/articles/scripts.md) incorrectly.

**Comment by jibran** [comment]
It is also happening to me on ubuntu.

**Comment by RobLoach** [comment]
Do note the path... [FileSystem\FilesystemStack] mkdir ["\/tmp\/\/drupal-scaffold-1460255831"]

/tmp//drupal-*. Would the paths have anything to do with it?

**Comment by webflo** [comment]
Tagged a new release with #28 and #30

**Comment by jibran** [comment]
This is not fixed yet. This is apparently the problem in robo extract/rename task. The extract task extract the file in some random tmp directory in project root. In `RoboFile.php` we have
```php
$extract = $this->taskExtract($archivePath)->to("$tmpDir/$fetchDirName")->run();
```
 And in `Extract.php` we have 
```php

            if ($hasEncapsulatingFolder && !$this->preserveTopDirectory) {
                $result = (new FileSystemStack())->rename($filesInExtractLocation[0], $this->to)->run();
                @rmdir($extractLocation);
            }
```
The directory `$extractLocation` is not empty so it is not deleted. `$extractLocation` is not empty because  `FilesystemStack::_rename` just copies the content to target and doesn't empties `$origin`.

**Comment by jibran** [comment]
There was fix in https://github.com/Codegyre/Robo/pull/276 but then there was https://github.com/Codegyre/Robo/pull/277 cc: @greg-1-anderson.

**Comment by webflo** [comment]
Hmm but, robo 0.7.* is required by drupal-composer/drupal-scaffold already.

**Comment by webflo** [comment]
@jibran @RobLoach could you try again with the latest release?

**Comment by greg-1-anderson** [comment]
@jibran @RobLoach There were still a couple of cross-volume rename bugs in Robo. This is not too surprising, considering that there were no cross-volume rename tests on Travis (since Travis does not have multiple volumes available). I refactored the code so that the cross-volume rename method was testable on a single volume, fixed the bugs, added a test, and tagged Robo 0.7.2.  Please run `composer update`, ensure that you got Robo 0.7.2, and see if it clears up your problems.

**Comment by jibran** [comment]
Thanks @greg-1-anderson robo 0.7.2 fixed the problem for me. Thanks @webflo for looking into it.

**Comment by greg-1-anderson** [comment]
Thanks for your patience, all.
