### ISSUE TITLE
Install through a Package?

### ISSUE THREAD

**Issue by RobLoach** [drupal-composer/drupal-scaffold#37]
Downloading Drupal just for the sites directory and the root files can be slow. Thought we may be able to handle this directly with a Composer package.

Experimented with this at a `drupal/root` project at https://github.com/RobLoach/root .

**Comment by RobLoach** [comment]
Have `drupal-scaffold` depend on `drupal/root`, and then have it symlink the files from `drupal/root` into the docroot? May speed up the process.

**Comment by webflo** [comment]
The ``drupal/root`` package is incomplete for scaffolding purpose because the scaffold populates sites/default as well. see https://github.com/drupal-composer/drupal-scaffold/blob/master/src/Handler.php#L353

**Comment by RobLoach** [comment]
Made an [issue for the sites directory](https://github.com/RobLoach/root/issues/1).

**Comment by webflo** [comment]
I like the idea in general and would like to have a faster setup, but the we need the scaffold command only once for the initial update (and for core updates). It increases the complexity a lot (new composer package, new automated subtree split) i am not sure if it's worth it.

**Comment by webflo** [comment]
Other idea: Rewrite drupal-scaffold and use http://cgit.drupalcode.org/ directly. We few downloads via http should be faster than current download-unpack-rsync dance. It exposes branches and tags via http and should be fairly up to date. http://cgit.drupalcode.org/drupal/plain/.htaccess?h=8.1.x

**Comment by greg-1-anderson** [comment]
I don't like the `drupal/root` project as much. The concept of drupal-scaffold is that the scaffold files are "owned" by the user's project; drupal-scaffold is just a mechanism to make it easier to update them when necessary. Hopefully this happens rarely, but depending on the project setup, it might happen every time on the CI server (although I think it is a better practice to commit the scaffold files so that this does not happen).

I like the idea of pulling files directly from http://cgit.drupalcode.org/ directly, though; new techniques that speed up the process without introducing a new subtree split project would be a win all around.

**Comment by webflo** [comment]
I put in together in #38

**Comment by RobLoach** [comment]
Another solution would be to symlink the assets with https://github.com/ajgarlag/AjglComposerSymlinker . I believe the symlink definitions would need to be in the root directory, though. So #38 is a cleaner solution. Well done, webflo!

**Comment by webflo** [comment]
Merged #38 a few minutes ago.
