### ISSUE TITLE
Patching the scaffold files

### ISSUE THREAD

**Issue by Aeotrin** [drupal-composer/drupal-scaffold#45]
What is the recommended method for handling changes to any of the files that scaffolding pulls down.
Patching them doesnt seem like a valid option as the files arent part of a specific project known to composer.

**Comment by webflo** [comment]
You can copy existing files from your own repo. The functionality was added in https://github.com/drupal-composer/drupal-scaffold/pull/44/files

**Comment by mike-potter** [comment]
I would like to see better support for patching files that scaffolding pulls down also.  Copying existing files from my own repo, or adding files to the "excludes" section is not an ideal solution.  Specifically for a file like .htaccess I'd like to apply a patch to whatever is downloaded.  Then if the .htaccess is updated by the master, the patch can still be properly merged.  Otherwise you are essentially "forked" from the core files.

Without adding a dependency to the composer-patcher system, one solution could be to simply execute a script when scaffolding is complete.  Something similar to the ``post-update-cmd``, which unfortunately fires *before* scaffolding is run.

**Comment by greg-1-anderson** [comment]
Try `post-drupal-scaffold-cmd`

**Comment by mike-potter** [comment]
Thanks, this worked great!
```
        "post-drupal-scaffold-cmd": [
            "cd docroot && patch -p1 <../patches/htaccess-ssl.patch"
        ]
```
